# Generated by Django 4.1.2 on 2022-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_host_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000', editable=False, null=True),
        ),
    ]
