# Generated by Django 4.1.2 on 2022-11-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_rename_id_author_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='id',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
