# Generated by Django 4.1.2 on 2022-11-22 03:58

from django.db import migrations

def populate_id(apps, schema_editor):
    author_model = apps.get_model('author', 'Author')
    for row in author_model.objects.all():
        row.id = row.url
        row.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_author_id'),
    ]

    operations = [
        migrations.RunPython(populate_id, reverse_code=migrations.RunPython.noop),
    ]
