# Generated by Django 4.1.2 on 2022-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(blank=True, editable=False, max_length=2048, null=True),
        ),
    ]
