# Generated by Django 4.1.2 on 2022-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.URLField(default='<django.db.models.fields.URLField>/comments', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(editable=False, max_length=500, null=True),
        ),
    ]
