# Generated by Django 4.1.2 on 2022-11-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_id_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
