# Generated by Django 4.1.2 on 2022-11-22 16:32

from django.db import migrations

def populate_id(apps, schema_editor):
    post_model = apps.get_model('post', 'Post')
    for row in post_model.objects.all():
        row.id = row.url
        row.save(update_fields=['id'])

class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_id'),
    ]

    operations = [
        migrations.RunPython(populate_id, reverse_code=migrations.RunPython.noop),
    ]
