# Generated by Django 4.1.2 on 2022-11-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('followers', '0001_initial'),
        ('like', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', editable=False, max_length=5)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inbox', serialize=False, to='author.author')),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='inbox_friend_request', to='followers.friendrequest')),
                ('likes', models.ManyToManyField(blank=True, related_name='inbox_like', to='like.like')),
                ('posts', models.ManyToManyField(blank=True, related_name='inbox_post', to='post.post')),
            ],
        ),
    ]
