# Generated by Django 4.1.2 on 2022-10-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_alter_post_title'),
        ('author', '0004_alter_author_host'),
        ('followers', '0006_rename_freindrequest_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', editable=False, max_length=5)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inbox', serialize=False, to='author.author')),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='inbox_friend_request', to='followers.friendrequest')),
                ('posts', models.ManyToManyField(blank=True, related_name='inbox_post', to='post.post')),
            ],
        ),
    ]
