# Generated by Django 4.1.2 on 2022-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_alter_like_author'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='inbox_like', to='like.like'),
        ),
    ]
