# Generated by Django 4.1.2 on 2022-10-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0003_alter_author_host_alter_author_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Follow', editable=False, max_length=6)),
                ('summary', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_request', to='author.author')),
                ('object', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recieved_follow_request', to='author.author')),
            ],
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'object'), name='unique_friend_request'),
        ),
    ]
