# Generated by Django 4.1.2 on 2022-10-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_alter_followrequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
