# Generated by Django 4.1.2 on 2022-10-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_host'),
        ('followers', '0005_freindrequest_delete_followrequest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreindRequest',
            new_name='FriendRequest',
        ),
    ]
